name: Notion to Markdown

on:
  # schedule:
  #   - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: meixg/blog-hexo-content
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: ls
        run: ls -all
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm ci
          node local-scripts/index.js
          ls -all -R output
          rm -rf source/_posts/*
          mv output/* source/_posts
          npm run build
        env:
          CI: true
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]; then
              echo "has_changes=true" >> $GITHUB_ENV
          else
              echo "has_changes=false" >> $GITHUB_ENV
          fi
      - name: Update algolia
        if: env.has_changes == 'true'
        run: |
          npm run algolia
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
      - name: Update leancloud
        if: env.has_changes == 'true'
        run: |
          npx hexo d || echo ""
      - name: Commit
        if: env.has_changes == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add . && git commit -m "update" || echo ""
          git push origin main
      - name: Publish to Cloudflare Pages
        if: env.has_changes == 'true'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 39a9a20457ce819632c53674af433303
          projectName: meixg-blog-notion
          directory: public
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
